#### 1번

아래 그림과 같은 DataFrame 을 생성하고,
변수 이름을 fruits 로 저장하세요.

|   | Apples        | Bananas      |
| - | ------------- | ------------ |
| 0 | 30  | 21 |

In [2]:
import pandas as pd

# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})

# Check your answer
# q1.check()
fruits

   Apples  Bananas
0      30       21

#### 2번

아래 그림과 같은 DataFrame 을 만들고
fruit_sales 변수에 저장하세요.

|   | Apples        | Bananas      |
| - | ------------- | ------------ |
| 2017 Sales | 35  | 21 |
| 2018 Sales | 41  | 34 |

In [4]:
fruit_sales = pd.DataFrame({'Apples': [35, 41], 'Bananas': [21, 34]}, index=['2017 Sales', '2018 Sales'])

# Check your answer
# q2.check()
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

#### 3번

아래와 같은 Series 를 만들고
변수 이름을 ingredients 로 저장하세요.

출력 형태:
```python
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can

Name: Dinner, dtype: object
```

In [7]:
ingredients = pd.Series({'Flour': '4 cups', 'Milk': '1 cup', 'Eggs': '2 large', 'Spam': '1 can'}, name = 'Dinner')

# Check your answer
# q3.check()
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

#### 4번

와인 리뷰 CSV 파일을 읽어서
reviews 라는 DataFrame 으로 저장하세요.

CSV 파일 경로:
```python
../input/wine-reviews/winemag-data_first150k.csv
```

In [ ]:
reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv', index_col=0)

# 정답 확인
# q4.check()

reviews

#### 5번

아래 코드를 실행하면
animals DataFrame 이 생성됩니다.

```python
animals = pd.DataFrame(
    {
        'Cows': [12, 20],
        'Goats': [22, 19]
    },
    index=['Year 1', 'Year 2']
)

animals
```

결과:
|        | Cows | Goats |
| ------ | ---- | ----- |
| Year 1 | 12   | 22    |
| Year 2 | 20   | 19    |
이 DataFrame 을 CSV 파일로 저장하세요.

파일 이름:
```python
cows_and_goats.csv
```

In [ ]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

animals.to_csv('cows_and_goats.csv')

        Cows  Goats
Year 1    12     22
Year 2    20     19